# Generated by Django 5.2.17 on 2026-08-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('price', models.BigIntegerField(verbose_name='price')),
                ('original_price', models.BigIntegerField(blank=True, null=True, verbose_name='original price')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='images')),
                ('colors', models.JSONField(blank=True, default=list, verbose_name='colors')),
                ('sizes', models.JSONField(blank=True, default=list, verbose_name='sizes')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='material')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('rating', models.FloatField(default=0.0, verbose_name='rating')),
                ('reviews', models.IntegerField(default=0, verbose_name='reviews count')),
                ('sold', models.IntegerField(default=0, verbose_name='sold count')),
                ('stock', models.IntegerField(default=0, verbose_name='stock count')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('new_arrival', models.BooleanField(default=False, verbose_name='new arrival')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
